import type { Metadata } from "next";
import { Protest_Guerrilla} from "next/font/google";
import { Revalia } from "next/font/google";
import "./globals.css";

const inter = Protest_Guerrilla({ subsets: ["latin"], weight: '400' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}


